"""add garages

Revision ID: 6d57ab4ebee8
Revises: b21ef2e9e4ab
Create Date: 2026-03-02 13:57:41.793643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d57ab4ebee8'
down_revision: Union[str, Sequence[str], None] = 'b21ef2e9e4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garages_id'), 'garages', ['id'], unique=False)
    op.create_index(op.f('ix_garages_user_id'), 'garages', ['user_id'], unique=True)
    op.create_table('garage_cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garage_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['garage_id'], ['garages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garage_id', 'car_id', name='uq_garage_car')
    )
    op.create_index(op.f('ix_garage_cars_car_id'), 'garage_cars', ['car_id'], unique=False)
    op.create_index(op.f('ix_garage_cars_garage_id'), 'garage_cars', ['garage_id'], unique=False)
    op.create_index(op.f('ix_garage_cars_id'), 'garage_cars', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_garage_cars_id'), table_name='garage_cars')
    op.drop_index(op.f('ix_garage_cars_garage_id'), table_name='garage_cars')
    op.drop_index(op.f('ix_garage_cars_car_id'), table_name='garage_cars')
    op.drop_table('garage_cars')
    op.drop_index(op.f('ix_garages_user_id'), table_name='garages')
    op.drop_index(op.f('ix_garages_id'), table_name='garages')
    op.drop_table('garages')
    # ### end Alembic commands ###
